### ISSUE TITLE
Autofill COM Ports does not work

### ISSUE THREAD

**Issue by irowebbn** [MSU-BOREALIS/AntennaTracker_withRFD#3]
When I try to run this from Spyder with all of my devices plugged in (Arduino, RFD, Maestro), I get the following error on line 1472:

`if (eachLst[1].Find("Arduino Uno") != -1) or (each.pid == 67):`

`IndexError: list index out of range`

If I do not plug anything in, I can launch the GUI. When I type in the COM ports manually, clicking "Update Settings" does nothing.

I've fiddled with changing the list index to zero, which gets rid of that error but doesn't actually get the port number or pid/vid or anything.

How are you able to read the COM ports correctly?

**Comment by irowebbn** [comment]
From what I can tell, printing out the ports would give something like this: 
`('COM4', 'Arduino Uno Programming Port (COM4)', 'USB VID:PID=2341:003D SNR=75330303035351300230')`

You are then trying to split this up into substrings by hyphen. However, this looks like an group of strings, and there are no hyphens, which would explain why asking for the second string after splitting gives an error. I think maybe using `if (each[1].Find("Arduino Uno") != -1 ) or (each[2].Find("67") != -1):` would work, but I need to test that to be sure.

I could be wrong, but that's how the port thing appears to work. [Source](https://stackoverflow.com/questions/24214643/python-to-automatically-select-serial-ports-for-arduino)

**Comment by trevor-gahl** [comment]
If the COM ports aren't automatically populating you likely need to update your pyserial library.
